#!/bin/bash

# Use the find command to locate all directories (including hidden directories) in the current directory
# and subdirectories, excluding the current and parent directories, and count them using the wc command
dir_count=$(find . -mindepth 1 -maxdepth 1 -type d -name ".*" -o -type d -print | wc -l)

echo "The number of directories and sub-directories in the current directory is: $dir_count"

